package com.example.compiler.semantic.emitter;

import com.example.compiler.yacc.ast.AstKind;
import com.example.compiler.yacc.ast.CoreAstNode;

import java.util.ArrayList;
import java.util.List;

/**
 * yysemantic.c 生成器。
 *
 * <p>输入是经过语义检查的 Core AST；输出是一份 C 源程序文本。该 C 程序被
 * gcc 编译运行后，会按照 Core AST 的动态语义打印 LLVM IR。这样项目就能
 * 贴近课程图中“语义引擎 -> yysemantic.c -> C 编译器 -> 可执行中间代码生成程序
 * -> LLVM IR”的路线。</p>
 *
 * <p>当前支持项目定义的 MiniC 子集：函数、参数、变量声明/赋值、return、
 * if/while、二元整数表达式和函数调用；不是完整 C99 语义发射器。</p>
 */
public final class CSemanticProgramEmitter {
    private int cValueCounter;

    /**
     * 生成完整 yysemantic.c 文本。
     *
     * @param coreRoot Core AST 根节点
     * @return 可由 gcc 编译的 C 源码
     */
    public String emit(CoreAstNode coreRoot) {
        StringBuilder out = new StringBuilder();
        emitHeader(out);
        emitRuntime(out);
        emitProgramActions(out, coreRoot);
        return out.toString();
    }

    private void emitProgramActions(StringBuilder out, CoreAstNode coreRoot) {
        expectKind(coreRoot, AstKind.PROGRAM);
        // yysemantic.c 自身是一个“中间代码生成程序”。
        // 它的 main 不等于用户程序 main，而是依次执行 Core AST 对应的发射动作。
        out.append("int main(void) {\n");
        out.append("    puts(\"; generated by yysemantic.c\");\n");
        out.append("    puts(\"\");\n");
        for (CoreAstNode function : coreRoot.getChildren()) {
            emitFunction(out, function);
        }
        out.append("    return 0;\n");
        out.append("}\n");
    }

    private void emitFunction(StringBuilder out, CoreAstNode node) {
        if (node.getKind() != AstKind.FUNCTION_DEF && node.getKind() != AstKind.MAIN_FUNCTION) {
            throw new IllegalStateException("Expected function node but got " + node.getKind());
        }

        List<String> params = new ArrayList<>();
        for (int i = 0; i < node.getChildren().size() - 1; i++) {
            CoreAstNode param = node.getChildren().get(i);
            expectKind(param, AstKind.PARAMETER);
            params.add(param.getText());
        }

        out.append("    begin_function(\"").append(cString(node.getText())).append("\", ")
                .append(params.size()).append(", ");
        if (params.isEmpty()) {
            out.append("NULL");
        } else {
            // 参数名作为字符串数组传给运行时 begin_function，
            // 运行时会为参数生成函数签名和 entry 中的 alloca/store。
            out.append("(const char*[]){");
            for (int i = 0; i < params.size(); i++) {
                if (i > 0) out.append(", ");
                out.append("\"").append(cString(params.get(i))).append("\"");
            }
            out.append("}");
        }
        out.append(");\n");

        emitBlock(out, node.getChildren().get(node.getChildren().size() - 1));
        out.append("    end_function();\n\n");
    }

    private void emitBlock(StringBuilder out, CoreAstNode node) {
        expectKind(node, AstKind.BLOCK);
        for (CoreAstNode child : node.getChildren()) {
            emitStatement(out, child);
        }
    }

    private void emitStatement(StringBuilder out, CoreAstNode node) {
        switch (node.getKind()) {
            case DECLARATION -> emitDeclaration(out, node);
            case ASSIGNMENT -> emitAssignment(out, node);
            case EXPRESSION_STMT -> {
                String ignored = emitExpression(out, node.getChildren().get(0));
                out.append("    (void)").append(ignored).append(";\n");
            }
            case RETURN_STMT -> {
                String value = emitExpression(out, node.getChildren().get(0));
                out.append("    emit_return(").append(value).append(");\n");
            }
            case IF_STMT -> emitIf(out, node);
            case WHILE_STMT -> emitWhile(out, node);
            case BLOCK -> emitBlock(out, node);
            default -> throw new IllegalStateException("Unsupported statement for C semantic emitter: " + node.getKind());
        }
    }

    private void emitDeclaration(StringBuilder out, CoreAstNode node) {
        CoreAstNode identifier = node.getChildren().get(0);
        // 声明先通知运行时登记变量栈槽；若有初始化表达式，再发射 store。
        out.append("    declare_variable(\"").append(cString(identifier.getText())).append("\");\n");
        if (node.getChildren().size() >= 2) {
            String value = emitExpression(out, node.getChildren().get(1));
            out.append("    emit_store(\"").append(cString(identifier.getText())).append("\", ").append(value).append(");\n");
        }
    }

    private void emitAssignment(StringBuilder out, CoreAstNode node) {
        String target = node.getChildren().get(0).getText();
        String value = emitExpression(out, node.getChildren().get(1));
        out.append("    emit_store(\"").append(cString(target)).append("\", ").append(value).append(");\n");
    }

    private void emitIf(StringBuilder out, CoreAstNode node) {
        String condition = emitExpression(out, node.getChildren().get(0));
        String elseLabel = nextCValue();
        String endLabel = nextCValue();

        // if/else 不直接打印固定 label 名，而是让 yysemantic.c 运行时生成唯一标签，
        // 避免嵌套控制流时标签冲突。
        out.append("    const char* ").append(elseLabel).append(" = new_label(\"L\");\n");
        if (node.getChildren().size() == 2) {
            out.append("    emit_if_false(").append(condition).append(", ").append(elseLabel).append(");\n");
            emitStatement(out, node.getChildren().get(1));
            out.append("    emit_label(").append(elseLabel).append(");\n");
            return;
        }

        out.append("    const char* ").append(endLabel).append(" = new_label(\"L\");\n");
        out.append("    emit_if_false(").append(condition).append(", ").append(elseLabel).append(");\n");
        emitStatement(out, node.getChildren().get(1));
        out.append("    emit_goto(").append(endLabel).append(");\n");
        out.append("    emit_label(").append(elseLabel).append(");\n");
        emitStatement(out, node.getChildren().get(2));
        out.append("    emit_label(").append(endLabel).append(");\n");
    }

    private void emitWhile(StringBuilder out, CoreAstNode node) {
        String startLabel = nextCValue();
        String endLabel = nextCValue();
        // while 的结构为：循环头标签 -> 条件 -> 条件假跳出 -> 循环体 -> 回跳循环头。
        out.append("    const char* ").append(startLabel).append(" = new_label(\"L\");\n");
        out.append("    const char* ").append(endLabel).append(" = new_label(\"L\");\n");
        out.append("    emit_label(").append(startLabel).append(");\n");
        String condition = emitExpression(out, node.getChildren().get(0));
        out.append("    emit_if_false(").append(condition).append(", ").append(endLabel).append(");\n");
        emitStatement(out, node.getChildren().get(1));
        out.append("    emit_goto(").append(startLabel).append(");\n");
        out.append("    emit_label(").append(endLabel).append(");\n");
    }

    private String emitExpression(StringBuilder out, CoreAstNode node) {
        return switch (node.getKind()) {
            case IDENTIFIER -> {
                String value = nextCValue();
                // 标识符表达式运行时对应一次 load，返回的字符串是 LLVM 临时值名。
                out.append("    const char* ").append(value).append(" = emit_load(\"")
                        .append(cString(node.getText())).append("\");\n");
                yield value;
            }
            case INT_LITERAL -> {
                String value = nextCValue();
                // 整数字面量不需要生成 LLVM 指令，运行时直接把常量文本作为值返回。
                out.append("    const char* ").append(value).append(" = literal(\"")
                        .append(cString(node.getText())).append("\");\n");
                yield value;
            }
            case BINARY_EXPR -> emitBinaryExpression(out, node);
            case FUNCTION_CALL -> emitFunctionCall(out, node);
            default -> throw new IllegalStateException("Unsupported expression for C semantic emitter: " + node.getKind());
        };
    }

    private String emitBinaryExpression(StringBuilder out, CoreAstNode node) {
        String left = emitExpression(out, node.getChildren().get(0));
        String right = emitExpression(out, node.getChildren().get(1));
        String value = nextCValue();
        String op = node.getText();
        // 比较运算和算术运算都用 emit_binary，isCompare 标记决定运行时生成
        // icmp 还是 add/sub/mul/sdiv。
        out.append("    const char* ").append(value).append(" = emit_binary(\"")
                .append(cString(llvmOp(op))).append("\", ")
                .append(left).append(", ").append(right).append(", ")
                .append(isCompare(op) ? "1" : "0").append(");\n");
        return value;
    }

    private String emitFunctionCall(StringBuilder out, CoreAstNode node) {
        List<String> args = new ArrayList<>();
        for (CoreAstNode arg : node.getChildren()) {
            args.add(emitExpression(out, arg));
        }

        String value = nextCValue();
        // 函数调用把已求值的参数临时值数组传给运行时，运行时输出 call 指令。
        out.append("    const char* ").append(value).append(" = emit_call(\"")
                .append(cString(node.getText())).append("\", ")
                .append(args.size()).append(", ");
        if (args.isEmpty()) {
            out.append("NULL");
        } else {
            out.append("(const char*[]){");
            for (int i = 0; i < args.size(); i++) {
                if (i > 0) out.append(", ");
                out.append(args.get(i));
            }
            out.append("}");
        }
        out.append(");\n");
        return value;
    }

    private String nextCValue() {
        return "v" + (++cValueCounter);
    }

    private static String llvmOp(String op) {
        return switch (op) {
            case "+" -> "add";
            case "-" -> "sub";
            case "*" -> "mul";
            case "/" -> "sdiv";
            case "<" -> "slt";
            case "<=" -> "sle";
            case ">" -> "sgt";
            case ">=" -> "sge";
            case "==" -> "eq";
            case "!=" -> "ne";
            default -> throw new IllegalStateException("Unsupported operator: " + op);
        };
    }

    private static boolean isCompare(String op) {
        return switch (op) {
            case "<", "<=", ">", ">=", "==", "!=" -> true;
            default -> false;
        };
    }

    private static void expectKind(CoreAstNode node, AstKind expected) {
        if (node.getKind() != expected) {
            throw new IllegalStateException("Expected " + expected + " but got " + node.getKind());
        }
    }

    private static String cString(String text) {
        return text.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static void emitHeader(StringBuilder out) {
        out.append("#include <stdio.h>\n");
        out.append("#include <stdlib.h>\n");
        out.append("#include <string.h>\n\n");
    }

    private static void emitRuntime(StringBuilder out) {
        out.append("""
typedef struct {
    char name[64];
    char slot[80];
} Slot;

static Slot slots[256];
static int slot_count = 0;
static int temp_count = 0;
static int label_count = 0;
static int block_terminated = 0;

static char* dup_text(const char* text) {
    char* copy = (char*)malloc(strlen(text) + 1);
    if (!copy) exit(2);
    strcpy(copy, text);
    return copy;
}

static char* format_text(const char* prefix, int number) {
    char buffer[64];
    snprintf(buffer, sizeof(buffer), "%s%d", prefix, number);
    return dup_text(buffer);
}

static const char* literal(const char* text) {
    return text;
}

static const char* new_temp(void) {
    return format_text("%t", ++temp_count);
}

static const char* new_value(void) {
    return format_text("%v", ++temp_count);
}

static const char* new_label(const char* prefix) {
    char buffer[64];
    snprintf(buffer, sizeof(buffer), "%s%d", prefix, ++label_count);
    return dup_text(buffer);
}

static int is_immediate(const char* value) {
    int i = 0;
    if (value[0] == '-') i = 1;
    if (value[i] == '\\0') return 0;
    for (; value[i] != '\\0'; i++) {
        if (value[i] < '0' || value[i] > '9') return 0;
    }
    return 1;
}

static const char* ensure_slot(const char* name) {
    for (int i = 0; i < slot_count; i++) {
        if (strcmp(slots[i].name, name) == 0) return slots[i].slot;
    }
    snprintf(slots[slot_count].name, sizeof(slots[slot_count].name), "%s", name);
    snprintf(slots[slot_count].slot, sizeof(slots[slot_count].slot), "%%%s.addr", name);
    printf("  %s = alloca i32, align 4\\n", slots[slot_count].slot);
    return slots[slot_count++].slot;
}

static void declare_variable(const char* name) {
    ensure_slot(name);
}

static const char* value_i32(const char* value) {
    if (is_immediate(value) || value[0] == '%') return value;
    const char* slot = ensure_slot(value);
    const char* loaded = new_value();
    printf("  %s = load i32, ptr %s, align 4\\n", loaded, slot);
    return loaded;
}

static const char* emit_load(const char* name) {
    const char* slot = ensure_slot(name);
    const char* loaded = new_value();
    printf("  %s = load i32, ptr %s, align 4\\n", loaded, slot);
    return loaded;
}

static void emit_store(const char* name, const char* value) {
    const char* slot = ensure_slot(name);
    printf("  store i32 %s, ptr %s\\n", value_i32(value), slot);
    block_terminated = 0;
}

static const char* emit_binary(const char* op, const char* left, const char* right, int compare) {
    const char* result = new_temp();
    if (compare) {
        printf("  %s = icmp %s i32 %s, %s\\n", result, op, value_i32(left), value_i32(right));
    } else {
        printf("  %s = %s i32 %s, %s\\n", result, op, value_i32(left), value_i32(right));
    }
    block_terminated = 0;
    return result;
}

static const char* emit_call(const char* function_name, int argc, const char** args) {
    const char* result = new_temp();
    printf("  %s = call i32 @%s(", result, function_name);
    for (int i = 0; i < argc; i++) {
        if (i > 0) printf(", ");
        printf("i32 %s", value_i32(args[i]));
    }
    printf(")\\n");
    block_terminated = 0;
    return result;
}

static void emit_goto(const char* label) {
    printf("  br label %%%s\\n", label);
    block_terminated = 1;
}

static void emit_if_false(const char* condition, const char* false_label) {
    const char* then_label = new_label("bb");
    printf("  br i1 %s, label %%%s, label %%%s\\n", condition, then_label, false_label);
    printf("%s:\\n", then_label);
    block_terminated = 0;
}

static void emit_label(const char* label) {
    if (!block_terminated) emit_goto(label);
    printf("%s:\\n", label);
    block_terminated = 0;
}

static void emit_return(const char* value) {
    printf("  ret i32 %s\\n", value_i32(value));
    block_terminated = 1;
}

static void begin_function(const char* name, int argc, const char** params) {
    slot_count = 0;
    temp_count = 0;
    block_terminated = 0;
    printf("define i32 @%s(", name);
    for (int i = 0; i < argc; i++) {
        if (i > 0) printf(", ");
        printf("i32 %%%s", params[i]);
    }
    printf(") {\\n");
    printf("entry:\\n");
    for (int i = 0; i < argc; i++) {
        const char* slot = ensure_slot(params[i]);
        printf("  store i32 %%%s, ptr %s\\n", params[i], slot);
    }
}

static void end_function(void) {
    if (!block_terminated) {
        printf("  ret i32 0\\n");
    }
    printf("}\\n\\n");
}

""");
    }
}
